name: build

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:

  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
      - run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo run --example headless --no-default-features --features "glutin-window image-io"
